#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Current
version:      20030803
version_from: lib/Acme/Current.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
